version: "3.9"

services:
  elearning.database:
    image: postgres:latest
    container_name: Elearning.Database
    environment:
      - POSTGRES_DB=elearning
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  elearning.redis:
    image: redis:latest
    container_name: Elearning.Redis
    restart: always
    ports:
      - 6379:6379

  elearning.jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: Elearning.Jaeger
    ports:
      - 4317:4317
      - 4318:4318
      - 16686:16686
  elearning.rabbitmq:
    image: rabbitmq:3-management
    container_name: Elearning.RabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
    ports:
      - 5672:5672 # AMQP protocol port
      - 15672:15672 # Management UI port
    volumes:
      - ./.containers/rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
